### ISSUE TITLE
Error on starting server

### ISSUE THREAD

**Issue by fastesol** [xuset/web-dht#1]
Hi I got this error when I tried to run the server using following command
`npm start 8000`

Please check the attached screenshot

![screenshot 2017-08-04 08 48 39](https://user-images.githubusercontent.com/12485556/28953525-13ebdc16-78f2-11e7-8c66-3da6134b072d.png)

**Comment by xuset** [comment]
Hi @fastesol! Thanks for reporting this. It looks like the error is related to Windows which is not supported (I don't have Windows). If you manage to add Windows support I'll gladly merge a PR for it
