### ISSUE TITLE
Example fails with 426 upgrade required

### ISSUE THREAD

**Issue by workhorsy** [xuset/web-dht#2]
I just tried the example from the readme (tried on chrome, firefox, and brave on Debian Linux):

```bash
git clone https://github.com/xuset/web-dht/
cd web-dht
npm install
npm start 8000
```

When I load it in the browser I get this message in the js console:

```
Failed to load resource: the server responded with a status of 426 (Upgrade Required)
```

The only thing displayed in the browser is:
```
Upgrade Required
```

Am I doing something wrong?

**Comment by xuset** [comment]
The `index.html` file contains a UI for storing and retrieving data in the DHT while `npm start 8000` only starts the bootstrap nodejs peer in the DHT and does _not_ serve the `index.html` file. Usually what I do is just double click the `index.html` file and that opens it in the web browser. Once opened, a web peer is created that connects to the bootstrap nodejs peer which allows for data to be stored and retrieved from the DHT.

I hope that helps! Feel free to ask if anything needs clarifying 👍

**Comment by workhorsy** [comment]
ok. I didn't realize that the index.html wasn't served from the same server. I'll close this for now.

Thanks.
