### ISSUE TITLE
dht.lookup() return ip:port instead of node id

### ISSUE THREAD

**Issue by rg3l3dr** [xuset/web-dht#3]
Great job on an amazing project! I've been really impressed with how easy it was to use peer-relay in my application.  Before I was using peer-relay by itself to disseminate gossip messages about membership between peers.  Recently I tried plugging it into web-dht and was able to quickly get the socket interface working.  

For my use-case, I only need to associate keys with peer ids (in the traditional sense of Kademlia).  So using BitTorrent DHT I am having Peer A call dht.announce(key) followed by Peer B calling dht.lookup(key) after hearing the announce event, with the expected return value being the peer-relay ID of Peer A.

Instead, dht.lookup() returns the address of Peer A as host:port.  For example, I normally get something like 39.0.0.0:6380.  Looking at the BitTorrent DHT codebase I see that DHT.lookup() will only return the address, not the node ID.  After tracing the route between the core project, k-rpc, and k-rpc socket I was a little intimidated by the complexity of trying to rewire this workflow to return the Node ID.

Granted this is not a bug with your project, but I was wondering if you had encountered this issue before or had any thoughts on the best way to tackle it?  I see that in web-dht you are only using dht.put() and dht.get().  Unfortunately, I don't think that will work for my use case since any peer needs to be able to announce that they also hold a record associated with a key, which will change over time.  Meaning it would need to be a mutable put and the ECDSA key associated with the record would then have to be somehow shared amongst any member who wants to edit the DHT.  Maybe this could work by making the associated private key public, but it seems like a lot of complexity and defeats the whole purpose of signed entries in the first place.

--Jeremiah

**Comment by rg3l3dr** [comment]
Found the solution, simpler than I expected.

In bittorrent-dht, after peers are announced they are put into a record cache, but first encoded into the form ip:port.  Simply removing the encoding on set_record and the decoding on get_record then adjusting the on('peer') event to just return peer fixed the problem.  Now the full node id is put into the record cache and returned, this node Id then be used to create a direct connection with peer relay.

[Remove encoding here](https://github.com/webtorrent/bittorrent-dht/blob/master/client.js#L578-L581)
```javascript
DHT.prototype._addPeer = function (peer, infoHash, from) {
  this._peers.add(infoHash.toString('hex'), encodePeer(peer.host, peer.port))
  this.emit('announce', peer, infoHash, from)
}
```
[Remove decoding here](https://github.com/webtorrent/bittorrent-dht/blob/master/client.js#L464-L470)
```javascript
function emit (values, from) {
    if (!values) values = self._peers.get(infoHash.toString('hex'), 100)
    var peers = decodePeers(values)
    for (var i = 0; i < peers.length; i++) {
      self.emit('peer', peers[i], infoHash, from || null)
    }
  }
```

**Comment by xuset** [comment]
Hi Jeremiah! Sorry for the pretty late response, but I'm glad you found a solution to the problem! 😃 

Your solution seems like the best way to go about it due to a lot of (rightly made) assumptions about the data contained in the ip field of some packages. Using the peer's id as an ip certainly caused some problems for this project, but at the same time was necessary since the ip:port tuple is used to identify a peer. I guess really the core of the problem is that in kademlia the id needs to be much larger than the space provided by ipv4 addresses. Maybe the peer's id could be shoehorned into a ipv6 address but there is still a pretty significant loss in the id space from 20 bytes to 7. Anyways, I'm glad you found a solution!
